version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    entrypoint: ["/var/www/docker/entrypoint.sh"]
    # depends_on:
    #   - db
    # environment:
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=laravel
    #   - DB_PASSWORD=secret
    networks:
      - laravel

#   db:
#     image: mysql:8.0
#     container_name: laravel-db
#     restart: always
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#     ports:
#       - "3306:3306"
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#       - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel


volumes:
  dbdata:

networks:
  laravel:
